# Generated by Django 4.0.3 on 2022-03-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_orders', '0003_order_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',)},
        ),
    ]
